services:
  - type: web
    name: file-downloader-backend
    env: docker
    region: oregon
    plan: free
    healthCheckPath: /status
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: PORT
        value: 8080
